name: starting_point
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  get: ^4.6.6
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  introduction_screen: ^3.1.11
  flutter_otp_text_field: ^1.1.1
  http: ^1.1.0
  dartz: ^0.10.1
  shared_preferences: ^2.2.1
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  convex_bottom_bar: ^3.2.0
  material_design_icons_flutter: ^7.0.7296
  hive_flutter: ^1.1.0
  flutter_ringtone_player: ^3.2.0
  jiffy: ^6.2.1
  url_launcher: ^6.1.14
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
flutter_assets:
  assets_path: assets/
  output_path: lib/core/constant/
  filename: app_assets.dart
